spring:
  jpa:
    hibernate:
      ddl-auto: none
      ejb.naming_strategy_delegator: org.hibernate.cfg.naming.ImprovedNamingStrategyDelegator
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/copycat?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: copycat
    password: copycat
    driverClassName: com.mysql.jdbc.Driver

    timeBetweenEvictionRunsMillis: 3600000
    testWhileIdle: true
    validationQuery: SELECT 1

spring.http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

logging:
  level.: INFO
  level.al.copycat: DEBUG
  file: ./logs/copycat-server.log

copycat:
  download:
    root: /tmp
    content:
      root: ${copycat.download.root}/contents
    torrent:
      root: ${copycat.download.root}/torrent
      suffix: .torrnet
